
# Tên của quy trình công việc sẽ hiển thị trong tab "Actions" của repo
name: Deploy to GitHub Pages

# Quy trình này sẽ được kích hoạt khi nào
on:
  # Chạy khi có một commit được đẩy lên nhánh `main`
  push:
    branches:
      - main
  # Cho phép bạn chạy quy trình này thủ công từ tab Actions
  workflow_dispatch:

# Quyền hạn cần thiết để quy trình có thể ghi vào nhánh `gh-pages`
permissions:
  contents: read
  pages: write
  id-token: write

# Cấu hình để chỉ cho phép một lần triển khai tại một thời điểm
concurrency:
  group: "pages"
  cancel-in-progress: true

# Các công việc (jobs) sẽ được thực hiện
jobs:
  # Công việc duy nhất trong quy trình này có tên là "deploy"
  deploy:
    # Môi trường cần thiết để triển khai lên Pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    # Chạy trên một máy ảo Ubuntu phiên bản mới nhất
    runs-on: ubuntu-latest
    
    # Các bước (steps) sẽ được thực thi tuần tự
    steps:
      # Bước 1: Lấy code từ repository của bạn về máy ảo
      - name: Checkout code
        uses: actions/checkout@v4

      # Bước 2: Thiết lập môi trường GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Bước 3: Build code và tạo ra một "artifact" từ thư mục public
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./public # Chỉ định thư mục nguồn là 'public'
          destination: ./_site

      # Bước 4: Tải artifact lên GitHub Pages để triển khai
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Tải lên từ thư mục _site (kết quả của bước build)
          path: './_site'

      # Bước 5: Triển khai artifact lên GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
